

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8762/eureka/,http://${eureka.instance.hostname}:8763/eureka/
  server:
    enable-self-preservation: true
spring:
  profiles:
    active: register3
  application:
    name: eureka-server

---
spring:
  profiles: register1
eureka:
  instance:
    hostname: 127.0.0.1
server:
  port: 8761

---
spring:
  profiles: register2
eureka:
  instance:
    hostname: 127.0.0.1
server:
  port: 8762

---
spring:
  profiles: register3
eureka:
  instance:
    hostname: 127.0.0.1
server:
  port: 8763

