
spring:
  application:
    name: eureka-discovery-learn
  profiles:
    active: register1   #项目启动，确定使用哪个配置
eureka:
  client:
    register-with-eureka: false   # 不向服务中心注册自己。
    fetch-registry: false         # 是否需要从注册中心拉取数据。
    service-url:
      defaultZone: http://shenhuaxin1:8700/eureka/,http://shenhuaxin2:8701/eureka/,http://shenhuaxin3:8702/eureka/

---
server:
  port: 8700
spring:
  profiles: register1
eureka:
  instance:
    hostname: shenhuaxin1:8700
---
server:
  port: 8701

spring:
  profiles: register2

eureka:
  instance:
    hostname: shenhuaxin2:8701

---
server:
  port: 8702

spring:
  profiles: register3
eureka:
  instance:
    hostname: shenhuaxin3:8702