server:
  port: 8082
spring:
  application:
    name: shop-service-learn
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://shenhuaxin1:8700/eureka
  instance:
    instance-id: shop-service-learn
    prefer-ip-address: true