server:
  port: 8082
spring:
  application:
    name: shop-service-learn
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://shenhuaxin1:8700/eureka
  instance:
    instance-id: shop-service-learn
    prefer-ip-address: true
#Logger:
#  Level: FULL
#debug: true
logging:
  level:
    com.springcloud.learn.shop.service.learn.service.OrderService: debug

feign:
  hystrix:
    enabled: true