server:
  port: 0
spring:
  application:
    name: user-service-learn
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://shenhuaxin1:8761/eureka
  instance:
    instance-id: user-service-learn${random.long}
    prefer-ip-address: true