spring:
  application:
    name: order-service-learn


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka,http://127.0.0.1:8763/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8084
