spring:
  application:
    name: order-service-learn
  profiles:
    active: order3

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://shenhuaxin1:8761/eureka/,http://shenhuaxin2:8762/eureka/
  instance:
    hostname: shenhuaxin1
    appname: order-service-learn


---
spring:
  profiles: order1
server:
  port: 8083

---
spring:
  profiles: order2
server:
  port: 8084

---
spring:
  profiles: order3
server:
  port: 8085

